apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-node-udacity 
  labels:
    app: udagram-feed-node-udacity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-feed-node-udacity
  template:
    metadata:
      labels:
        app: udagram-feed-node-udacity
    spec:
      containers:
      - name: udagram-feed-node-udacity
        image: ta9i/udagram-feed-node-udacity
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"