apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-node-udacity 
  labels:
    app: udagram-feed-node-udacity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feed-node-udacity
  template:
    metadata:
      labels:
        app: udagram-feed-node-udacity
    spec:
      containers:
      - name: udagram-feed-node-udacity
        image: ta9i/udagram-feed-node-udacity
        ports:
        - containerPort: 80