apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-node-udacity 
  labels:
    app: udagram-feed-node-udacity
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: udagram-feed-node-udacity